# Generated by Django 4.1 on 2023-08-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('industry_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
                ('category_type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category_list',
            },
        ),
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_code', models.CharField(max_length=12)),
                ('cluster_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'clusters',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_type', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100, null=True)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('gstn', models.CharField(max_length=250, null=True)),
                ('pan', models.CharField(max_length=20, null=True)),
                ('number_of_shareholder', models.IntegerField(default=0)),
                ('purchase_email', models.EmailField(max_length=250, null=True)),
                ('purchase_contact_number', models.CharField(max_length=20, null=True)),
                ('accounts_email', models.EmailField(max_length=250, null=True)),
                ('accounts_contact_number', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=100)),
                ('company_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'company_types',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_uid', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=250)),
                ('department_type', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type', models.CharField(max_length=100)),
                ('department_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'department_types',
            },
        ),
        migrations.CreateModel(
            name='EmploymentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(max_length=100)),
                ('employment_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'employment_types',
            },
        ),
        migrations.CreateModel(
            name='HighValueItemTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_value_item_type', models.CharField(max_length=100)),
                ('high_value_item_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'high_value_item_types',
            },
        ),
        migrations.CreateModel(
            name='IndustryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(max_length=50)),
                ('industry_type_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'industry_type',
            },
        ),
        migrations.CreateModel(
            name='PosTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_type', models.CharField(max_length=100)),
                ('pos_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'pos_types',
            },
        ),
        migrations.CreateModel(
            name='PrioritiyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_type', models.CharField(max_length=100)),
                ('priority_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'priority_types',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('product_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='SeverityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_type', models.CharField(max_length=100)),
                ('severity_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'severity_types',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20, unique=True)),
                ('unit_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'unit_of_measurments',
            },
        ),
        migrations.CreateModel(
            name='VendorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=100)),
                ('vendor_type_description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'vendor_types',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=250, unique=True)),
                ('sub_category_type', models.CharField(max_length=250)),
                ('categories', models.ManyToManyField(blank=True, related_name='sub_categories', to='master_app.categorylist')),
            ],
            options={
                'db_table': 'sub_category_list',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=250)),
                ('document_url', models.TextField(null=True)),
                ('document_name', models.CharField(max_length=250, null=True)),
                ('document_description', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master_app.company')),
            ],
            options={
                'db_table': 'company_document',
            },
        ),
        migrations.CreateModel(
            name='UserBrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='master_app.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_brand_mapping',
                'unique_together': {('user', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='CompanyShareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='master_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_user_mapping',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CompanyCluserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='master_app.clusters')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='master_app.company')),
            ],
            options={
                'db_table': 'company_cluster_mapping',
                'unique_together': {('cluster', 'company')},
            },
        ),
        migrations.CreateModel(
            name='BrandClusterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='master_app.brand')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='master_app.clusters')),
            ],
            options={
                'db_table': 'brand_cluster_mapping',
                'unique_together': {('cluster', 'brand')},
            },
        ),
    ]
