# Generated by Django 4.1 on 2023-08-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentClusterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='master_app.clusters')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='master_app.department')),
            ],
        ),
    ]
