# Generated by Django 4.1 on 2023-08-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_departmentclustermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_code', models.CharField(max_length=50)),
                ('pos_name', models.CharField(max_length=100)),
                ('pos_type', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'pos',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=250)),
                ('address_line_1', models.TextField(null=True)),
                ('address_line_2', models.TextField(verbose_name=True)),
                ('landmark', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('pan', models.CharField(max_length=20, null=True)),
                ('gstn', models.CharField(max_length=50, null=True)),
                ('vendor_type', models.CharField(max_length=100, null=True)),
                ('credit_period', models.FloatField(default=0)),
                ('is_msme_registered', models.BooleanField(default=False)),
                ('msme_registration_number', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.AlterModelTable(
            name='departmentclustermapping',
            table='department_cluster_mapping',
        ),
        migrations.CreateModel(
            name='VendorDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=250)),
                ('document_url', models.TextField(null=True)),
                ('document_name', models.CharField(max_length=250, null=True)),
                ('document_description', models.TextField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master_app.vendors')),
            ],
            options={
                'db_table': 'vendor_documents',
            },
        ),
        migrations.CreateModel(
            name='VendorBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=240, null=True)),
                ('account_name', models.CharField(max_length=240, null=True)),
                ('account_number', models.CharField(max_length=240, null=True)),
                ('ifsc', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=240, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.vendors')),
            ],
            options={
                'db_table': 'vendor_bank_details',
            },
        ),
    ]
