# Generated by Django 4.1 on 2023-08-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_vendorclustermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='master_app.vendors'),
        ),
    ]
