# Generated by Django 4.1 on 2023-08-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_alter_vendorbankdetails_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPOSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='master_app.pos')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.vendors')),
            ],
            options={
                'db_table': 'vendor_pos_mapping',
            },
        ),
        migrations.CreateModel(
            name='VendorBrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='master_app.brand')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='master_app.vendors')),
            ],
            options={
                'db_table': 'vendor_brand_mapping',
            },
        ),
    ]
