# Generated by Django 4.1 on 2023-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_vendorposmapping_vendorbrandmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbankdetails',
            name='account_number',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
