# Generated by Django 4.1 on 2023-08-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_vendorposmapping_vendorbrandmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='master_app.clusters'),
        ),
        migrations.CreateModel(
            name='PosDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.department')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='master_app.pos')),
            ],
            options={
                'db_table': 'pos_department_mapping',
            },
        ),
        migrations.CreateModel(
            name='PosCompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.company')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='master_app.pos')),
            ],
            options={
                'db_table': 'pos_company_mapping',
            },
        ),
    ]
