# Generated by Django 4.1 on 2023-09-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0007_alter_vendorbankdetails_account_number'),
        ('master_app', '0007_pos_cluster_posdepartmentmapping_poscompanymapping'),
    ]

    operations = [
    ]
