# Generated by Django 4.1 on 2023-09-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0008_merge_20230902_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtoBclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=250)),
                ('address_line_1', models.TextField(null=True)),
                ('address_line_2', models.TextField(verbose_name=True)),
                ('landmark', models.TextField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('pan', models.CharField(max_length=20, null=True)),
                ('gstn', models.CharField(max_length=50, null=True)),
                ('billing_type', models.CharField(default='gst', max_length=20)),
                ('credit_period_days', models.IntegerField(default=0)),
                ('credit_period_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'b2b_client',
            },
        ),
        migrations.AlterUniqueTogether(
            name='poscompanymapping',
            unique_together={('pos', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='posdepartmentmapping',
            unique_together={('pos', 'department')},
        ),
        migrations.CreateModel(
            name='B2BclientBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=240, null=True)),
                ('account_name', models.CharField(max_length=240, null=True)),
                ('account_number', models.CharField(max_length=240, null=True, unique=True)),
                ('ifsc', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=240, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='master_app.btobclient')),
            ],
            options={
                'db_table': 'b2b_client_bank_details',
            },
        ),
    ]
