# Generated by Django 4.1 on 2023-09-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_store_alter_b2bratesdefination_item_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClusterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='master_app.clusters')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='master_app.store')),
            ],
            options={
                'db_table': 'store_cluster_mapping',
            },
        ),
        migrations.CreateModel(
            name='StoreBrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='master_app.brand')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='master_app.store')),
            ],
            options={
                'db_table': 'store_brand_mapping',
            },
        ),
        migrations.CreateModel(
            name='SemiProductRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('product_type', models.CharField(default='SP', max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('recipe_unit', models.CharField(max_length=50, null=True)),
                ('yield_quantity', models.FloatField(null=True)),
                ('yield_quantity_cost', models.FloatField(null=True)),
                ('food_cost', models.FloatField(null=True)),
                ('life_cycle', models.FloatField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('high_value_item', models.CharField(max_length=50, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('severity', models.CharField(max_length=50, null=True)),
                ('available_for_cluster', models.BooleanField(default=False)),
                ('cost_center_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center_department_sm', to='master_app.department')),
                ('production_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_department_sm', to='master_app.department')),
            ],
            options={
                'db_table': 'semi_product_registration',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('tax', models.FloatField(null=True)),
                ('product_type', models.CharField(default='RM', max_length=50)),
                ('hsn_code', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('recipe_unit', models.CharField(max_length=50, null=True)),
                ('flag_recipe_conversion_ratio', models.BooleanField(default=True)),
                ('recipe_conversion_ratio', models.FloatField(null=True)),
                ('recipe_rate', models.FloatField(default=0)),
                ('recipe_price', models.FloatField(default=0)),
                ('direct_selling', models.BooleanField(default=False)),
                ('life_cycle', models.FloatField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('high_value_item', models.CharField(max_length=50, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('severity', models.CharField(max_length=50, null=True)),
                ('available_for_cluster', models.BooleanField(default=False)),
                ('primary_vendor_rate', models.FloatField(default=0)),
                ('primary_vendor_price', models.FloatField(default=0)),
                ('secondary_vendor_rate', models.FloatField(default=0)),
                ('secondary_vendor_price', models.FloatField(default=0)),
                ('primary_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_vendor', to='master_app.vendors')),
                ('secondary_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_vendor', to='master_app.vendors')),
            ],
            options={
                'db_table': 'raw_material_registration',
            },
        ),
        migrations.CreateModel(
            name='FinalProductRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('product_type', models.CharField(default='FP', max_length=50)),
                ('production_cycle', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('recipe_unit', models.CharField(max_length=50, null=True)),
                ('yield_quantity', models.FloatField(null=True)),
                ('yield_quantity_cost', models.FloatField(null=True)),
                ('food_cost', models.FloatField(null=True)),
                ('life_cycle', models.FloatField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('high_value_item', models.CharField(max_length=50, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('severity', models.CharField(max_length=50, null=True)),
                ('available_for_cluster', models.BooleanField(default=False)),
                ('ratail_tax', models.FloatField(null=True)),
                ('b2b_tax', models.FloatField(null=True)),
                ('hsn_code', models.CharField(max_length=50, null=True)),
                ('department_selling_price', models.FloatField(null=True)),
                ('pos_selling_price', models.FloatField(null=True)),
                ('b2b_selling_price', models.FloatField(null=True)),
                ('cost_center_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center_department_fp', to='master_app.department')),
                ('production_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_department_fp', to='master_app.department')),
            ],
            options={
                'db_table': 'final_product_registration',
            },
        ),
    ]
