# Generated by Django 4.1 on 2023-09-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0015_remove_finalproductregistrationmodel_b2b_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproductregistrationmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_final_product', to='master_app.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialregistrationmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_raw_material', to='master_app.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semiproductregistrationmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_semi_product', to='master_app.brand'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FinalProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.finalproductregistrationmodel')),
            ],
            options={
                'db_table': 'final_product_tags',
            },
        ),
    ]
