# Generated by Django 4.1 on 2023-09-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0017_hsntaxinformation_hsncodetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproducttags',
            name='final_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_product_tags', to='master_app.finalproductregistrationmodel'),
        ),
    ]
