# Generated by Django 4.1 on 2023-09-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0018_alter_finalproducttags_final_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BRatesDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b2b_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_definition', to='master_app.btobclient')),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_rate_definition', to='master_app.finalproductregistrationmodel')),
            ],
            options={
                'db_table': 'b2b_rates_definition',
            },
        ),
        migrations.DeleteModel(
            name='B2BRatesDefination',
        ),
    ]
