# Generated by Django 4.1 on 2023-10-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0020_remove_finalproductregistrationmodel_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaterialRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('yield_quantity', models.FloatField(null=True)),
                ('yield_quantity_cost', models.FloatField(null=True)),
                ('life_cycle', models.FloatField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('high_value_item', models.BooleanField(null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('severity', models.CharField(max_length=50, null=True)),
                ('available_for_cluster', models.BooleanField(default=False)),
                ('hsn_code', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_service_material', to='master_app.brand')),
            ],
            options={
                'db_table': 'service_material_registration',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterialPosMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_material', to='master_app.pos')),
                ('service_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.servicematerialregistrationmodel')),
            ],
            options={
                'db_table': 'service_material_pos_mapping',
                'unique_together': {('service_material', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterialDeptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_material', to='master_app.department')),
                ('service_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='master_app.servicematerialregistrationmodel')),
            ],
            options={
                'db_table': 'service_material_dept_mapping',
                'unique_together': {('service_material', 'department')},
            },
        ),
    ]
