# Generated by Django 4.1 on 2023-10-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0021_servicematerialregistrationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_app.brand'),
        ),
        migrations.AddField(
            model_name='departmentclustermapping',
            name='food_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialregistrationmodel',
            name='production',
            field=models.BooleanField(default=True),
        ),
    ]
