# Generated by Django 4.1 on 2023-11-03 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0023_rename_created_date_store_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultVariableCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_charge_code', models.CharField(max_length=240, unique=True)),
                ('variable_charge', models.FloatField()),
                ('variable_charge_description', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'default_variable_charges',
            },
        ),
        migrations.CreateModel(
            name='RecipeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=240)),
                ('item_code', models.CharField(max_length=240)),
                ('product_type', models.CharField(max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_recipe_registrations', to='master_app.brand')),
                ('final_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_product_recipe', to='master_app.finalproductregistrationmodel')),
                ('production_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_department_recipe', to='master_app.department')),
                ('recipe_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_aprroved', to=settings.AUTH_USER_MODEL)),
                ('recipe_entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_entered', to=settings.AUTH_USER_MODEL)),
                ('semi_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_product_recipe', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'recipe_registration',
            },
        ),
        migrations.CreateModel(
            name='RecipeVariableCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_charge_code', models.CharField(max_length=240)),
                ('variable_charge', models.FloatField()),
                ('variable_charge_description', models.CharField(max_length=240)),
                ('latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_variable_charges', to='master_app.reciperegistration')),
            ],
            options={
                'db_table': 'recipe_variable_charges',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_code', models.CharField(max_length=240)),
                ('ingredient_name', models.CharField(max_length=240)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('yield_qauntity', models.FloatField(default=0)),
                ('yield_production_value', models.FloatField(default=0)),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_as_ingredient', to='master_app.rawmaterialregistrationmodel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='master_app.reciperegistration')),
                ('semi_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_product_as_ingredient', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'recipe_ingredients',
            },
        ),
    ]
