# Generated by Django 4.1 on 2023-11-03 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0024_defaultvariablecharges_reciperegistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvariablecharges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultvariablecharges',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultvariablecharges',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultvariablecharges',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
