# Generated by Django 4.1 on 2023-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0025_defaultvariablecharges_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperegistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='approved_on',
            field=models.DateTimeField(null=True),
        ),
    ]
