# Generated by Django 4.1 on 2023-11-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0028_semiproducttags_rawmaterialtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_department_uid', models.CharField(max_length=20)),
                ('sub_department_name', models.CharField(max_length=250)),
                ('sub_department_type', models.CharField(max_length=250, null=True)),
                ('target_food_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='master_app.department')),
            ],
            options={
                'db_table': 'sub_department',
            },
        ),
    ]
