# Generated by Django 4.1 on 2023-12-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0029_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSubdepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='master_app.pos')),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.subdepartment')),
            ],
            options={
                'db_table': 'pos_sub_department_mapping',
                'unique_together': {('pos', 'sub_department')},
            },
        ),
    ]
