# Generated by Django 4.1 on 2023-12-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0030_possubdepartmentmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='required_sub_department',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VendorbankDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master_app.vendorbankdetails')),
                ('vendor_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='master_app.vendordocuments')),
            ],
            options={
                'db_table': 'vendor_bank_documents',
            },
        ),
        migrations.CreateModel(
            name='StorePosMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='master_app.pos')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.store')),
            ],
            options={
                'db_table': 'store_pos_mapping',
            },
        ),
    ]
