# Generated by Django 4.1 on 2023-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0031_brand_required_sub_department_vendorbankdocuments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsntaxinformation',
            name='brand',
        ),
        migrations.CreateModel(
            name='VendorPricingUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(null=True)),
                ('new_value', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_log', to='master_app.vendorpricingrawmaterial')),
            ],
            options={
                'db_table': 'vendor_raw_material_pricing_log',
            },
        ),
    ]
