# Generated by Django 4.1 on 2023-12-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0032_remove_hsntaxinformation_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInvetoryDeptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_inventory_dept_mapping',
            },
        ),
        migrations.CreateModel(
            name='AssetInvetoryPosMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_inventory_pos_mapping',
            },
        ),
        migrations.CreateModel(
            name='AssetInvetoryRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('yield_quantity', models.FloatField(null=True)),
                ('yield_quantity_cost', models.FloatField(null=True)),
                ('life_cycle', models.FloatField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('high_value_item', models.BooleanField(null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('severity', models.CharField(max_length=50, null=True)),
                ('available_for_cluster', models.BooleanField(default=False)),
                ('hsn_code', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_asset_inventory', to='master_app.brand')),
            ],
            options={
                'db_table': 'asset_inventory_registration',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicematerialposmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicematerialposmapping',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='servicematerialposmapping',
            name='service_material',
        ),
        migrations.RemoveField(
            model_name='servicematerialregistrationmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='ServiceMaterialDeptMapping',
        ),
        migrations.DeleteModel(
            name='ServiceMaterialPosMapping',
        ),
        migrations.DeleteModel(
            name='ServiceMaterialRegistrationModel',
        ),
        migrations.AddField(
            model_name='assetinvetoryposmapping',
            name='asset_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.assetinvetoryregistrationmodel'),
        ),
        migrations.AddField(
            model_name='assetinvetoryposmapping',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_inventory', to='master_app.pos'),
        ),
        migrations.AddField(
            model_name='assetinvetorydeptmapping',
            name='asset_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='master_app.assetinvetoryregistrationmodel'),
        ),
        migrations.AddField(
            model_name='assetinvetorydeptmapping',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_inventory', to='master_app.department'),
        ),
        migrations.AlterUniqueTogether(
            name='assetinvetoryposmapping',
            unique_together={('asset_inventory', 'pos')},
        ),
        migrations.AlterUniqueTogether(
            name='assetinvetorydeptmapping',
            unique_together={('asset_inventory', 'department')},
        ),
    ]
