# Generated by Django 4.1 on 2023-12-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0033_assetinvetorydeptmapping_assetinvetoryposmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
                ('asset_type_description', models.CharField(max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.brand')),
            ],
            options={
                'db_table': 'asset_type_list',
            },
        ),
    ]
