# Generated by Django 4.1 on 2023-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0034_assettypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvetoryregistrationmodel',
            name='asset_type',
            field=models.CharField(default='asset_type', max_length=100),
            preserve_default=False,
        ),
    ]
