# Generated by Django 4.1 on 2023-12-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0035_assetinvetoryregistrationmodel_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiProductPosMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_product', to='master_app.pos')),
                ('semi_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'semi_product_pos_mapping',
                'unique_together': {('semi_product', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='SemiProductDeptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_product', to='master_app.department')),
                ('semi_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'semi_product_dept_mapping',
                'unique_together': {('semi_product', 'department')},
            },
        ),
    ]
