# Generated by Django 4.1 on 2023-12-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0035_assetinvetoryregistrationmodel_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='billing_address',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pos',
            name='shipping_address',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField()),
                ('address_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='master_app.company')),
            ],
            options={
                'db_table': 'company_address',
            },
        ),
        migrations.CreateModel(
            name='ClusterAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField()),
                ('address_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_address', to='master_app.clusters')),
            ],
            options={
                'db_table': 'cluster_address',
            },
        ),
        migrations.CreateModel(
            name='BrandAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField()),
                ('address_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_address', to='master_app.brand')),
            ],
            options={
                'db_table': 'brand_address',
            },
        )
    ]
