# Generated by Django 4.1 on 2023-12-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0036_pos_billing_address_pos_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialregistrationmodel',
            name='consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='remark',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='RecipePackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=240)),
                ('package_name', models.CharField(max_length=240)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_as_packging', to='master_app.rawmaterialregistrationmodel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_packaging', to='master_app.reciperegistration')),
            ],
            options={
                'db_table': 'recipe_packaging',
            },
        ),
    ]
