# Generated by Django 4.1 on 2023-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0037_rawmaterialregistrationmodel_consumable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialregistrationmodel',
            name='consumable',
            field=models.BooleanField(default=True),
        ),
    ]
