# Generated by Django 4.1 on 2023-12-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0036_semiproductposmapping_semiproductdeptmapping'),
        ('master_app', '0038_alter_rawmaterialregistrationmodel_consumable'),
    ]

    operations = [
    ]
