# Generated by Django 4.1 on 2023-12-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0039_merge_20231221_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproductregistrationmodel',
            old_name='yield_quantity_cost',
            new_name='packaging_cost',
        ),
        migrations.RenameField(
            model_name='semiproductregistrationmodel',
            old_name='yield_quantity_cost',
            new_name='packaging_cost',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='yield_production_value',
        ),
        migrations.AddField(
            model_name='finalproductregistrationmodel',
            name='variable_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='finalproductregistrationmodel',
            name='yield_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='food_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='ingredient_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='packaging_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='variable_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='yield_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reciperegistration',
            name='yield_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='semiproductregistrationmodel',
            name='variable_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='semiproductregistrationmodel',
            name='yield_value',
            field=models.FloatField(null=True),
        ),
    
    ]
