# Generated by Django 4.1 on 2024-01-15 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0040_rename_yield_quantity_cost_finalproductregistrationmodel_packaging_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperegistration',
            name='recipe_unit',
            field=models.CharField(default='KG', max_length=50),
            preserve_default=False,
        ),
        
    ]
