# Generated by Django 4.1 on 2024-01-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0041_reciperegistration_recipe_unit_poplanningmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_planning_id', models.CharField(max_length=50, null=True)),
                ('consumption_date_from', models.DateField(null=True)),
                ('consumption_date_to', models.DateField(null=True)),
                ('planned_date_from', models.DateField()),
                ('planned_date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_po_planing', to='master_app.store')),
            ],
            options={
                'db_table': 'po_planning_master',
            },
        ),
        migrations.CreateModel(
            name='PoPlanningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_date_from', models.DateField(null=True)),
                ('consumption_date_to', models.DateField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('consumable', models.BooleanField(default=True)),
                ('high_value_item', models.BooleanField(default=False)),
                ('planned', models.BooleanField(default=False)),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('current_stock_during_planning', models.FloatField(default=0)),
                ('ideal_order_qauntity', models.FloatField(default=0)),
                ('current_stock', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=240, null=True)),
                ('request_add_new_qauntity', models.BooleanField(default=False)),
                ('allowed_quantity', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('already_ordered_quantity', models.FloatField(default=0)),
                ('balance_qauntity', models.FloatField(default=0)),
                ('po_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_plan_material', to='master_app.poplanning')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_planning', to='master_app.rawmaterialregistrationmodel')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_planning', to='master_app.vendors')),
            ],
            options={
                'db_table': 'po_planning_material',
            },
        ),
    ]
