# Generated by Django 4.1 on 2024-01-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0042_poplanning_poplanningmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poplanningmaterial',
            name='consumption_date_from',
        ),
        migrations.RemoveField(
            model_name='poplanningmaterial',
            name='consumption_date_to',
        ),
    ]
