# Generated by Django 4.1 on 2024-01-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0043_remove_poplanningmaterial_consumption_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialregistrationmodel',
            name='default_uom_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RawMaterialUomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('uom', models.CharField(max_length=20)),
                ('recipe_unit', models.CharField(max_length=20)),
                ('defalt_uom_quantity', models.FloatField()),
                ('default_uom', models.CharField(max_length=20)),
                ('new_uom_quantity', models.FloatField()),
                ('new_uom', models.CharField(max_length=20)),
                ('new_uom_to_default_uom_ratio', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials_uom', to='master_app.rawmaterialregistrationmodel')),
            ],
            options={
                'db_table': 'raw_material_uoms',
            },
        ),
    ]
