# Generated by Django 4.1 on 2024-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0044_rawmaterialregistrationmodel_default_uom_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproductregistrationmodel',
            name='default_uom_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='semiproductregistrationmodel',
            name='default_uom_quantity',
            field=models.FloatField(default=0),
        ),
    ]
