# Generated by Django 4.1 on 2024-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0045_finalproductregistrationmodel_default_uom_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteraddress',
            name='use_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
