# Generated by Django 4.1 on 2024-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0046_clusteraddress_use_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteraddress',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
