# Generated by Django 4.1 on 2024-02-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0047_clusteraddress_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvariablecharges',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_default_variable_charges', to='master_app.brand'),
            preserve_default=False,
        ),
    ]
