# Generated by Django 4.1 on 2024-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0049_alter_defaultvariablecharges_variable_charge_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
