# Generated by Django 4.1 on 2024-02-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0050_companyaddress_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(max_length=50, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('billing_address', models.JSONField()),
                ('shipping_address', models.JSONField()),
                ('remark', models.CharField(max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_po', to='master_app.store')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_app.vendors')),
            ],
            options={
                'db_table': 'po_model',
            },
        ),
        migrations.CreateModel(
            name='PoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField(default=0)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('qty', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='master_app.pomodel')),
            ],
            options={
                'db_table': 'po_items',
            },
        ),
    ]
