# Generated by Django 4.1 on 2024-03-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0054_alter_vendors_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
