# Generated by Django 4.1 on 2024-03-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0055_alter_store_store_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='master_app.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='master_app.company')),
            ],
            options={
                'db_table': 'company_brand_mapping',
                'unique_together': {('brand', 'company')},
            },
        ),
    ]
