# Generated by Django 4.1 on 2024-03-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0056_companybrandmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurementConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit_quantity', models.FloatField()),
                ('convert_to_unit_quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convert_to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_to_unit_conversion', to='master_app.unitofmeasurement')),
                ('source_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_unit_conversion', to='master_app.unitofmeasurement')),
            ],
            options={
                'db_table': 'unit_of_measurment_conversion',
            },
        ),
    ]
