# Generated by Django 4.1 on 2024-03-11 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0057_unitofmeasurementconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodel',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_aproved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='manual_approved',
            field=models.BooleanField(default=False),
        ),
    ]
