# Generated by Django 4.1 on 2024-03-24 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0058_pomodel_approved_by_pomodel_auto_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_grn', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=240, null=True)),
                ('vendor_name', models.CharField(max_length=240)),
                ('address_line_1', models.TextField(null=True)),
                ('address_line_2', models.TextField(verbose_name=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('grn_timestamp', models.DateTimeField(auto_now=True)),
                ('amount_in_words', models.TextField()),
                ('grn_date', models.DateField()),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.FloatField()),
                ('grn_value', models.FloatField()),
                ('tax_value', models.FloatField(default=0)),
                ('grn_invoice_amount_diff', models.FloatField(default=0)),
                ('gstn', models.CharField(max_length=50, null=True)),
                ('gst_purchased', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchased',
            },
        ),
        migrations.AddField(
            model_name='pomodel',
            name='send_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poplanningmaterial',
            name='planned',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UnplannedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_po_planing_unplanned_items', to='master_app.store')),
            ],
            options={
                'db_table': 'store_unplanned_items',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialAliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_alias', to='master_app.rawmaterialregistrationmodel')),
            ],
            options={
                'db_table': 'raw_material_alias',
            },
        ),
        migrations.CreateModel(
            name='PurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField(default=0)),
                ('default_uom', models.CharField(blank=True, max_length=20, null=True)),
                ('tax', models.FloatField(null=True)),
                ('rate', models.FloatField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField(default=1)),
                ('tax_amount', models.FloatField(default=0)),
                ('without_tax_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='master_app.purchased')),
            ],
            options={
                'db_table': 'purchased_items',
            },
        ),
        migrations.AddField(
            model_name='purchased',
            name='po_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_purchased', to='master_app.pomodel'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_purchased', to='master_app.vendors'),
        ),
    ]
