# Generated by Django 4.1 on 2024-03-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0059_purchased_pomodel_send_approval_pomodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandaddress',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandaddress',
            name='use_for_all',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchaseditems',
            name='hsn',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='clusteraddress',
            name='use_for_all',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
