# Generated by Django 4.1 on 2024-03-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0060_brandaddress_short_name_brandaddress_use_for_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='address',
        ),
        # migrations.AlterField(
        #     model_name='companyaddress',
        #     name='address',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_company_address', to='master_app.brandaddress'),
        # ),
        # migrations.AlterField(
        #     model_name='pos',
        #     name='billing_address',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_pos_billing_address', to='master_app.brandaddress'),
        # ),
        # migrations.AlterField(
        #     model_name='pos',
        #     name='shipping_address',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_pos_shipping_address', to='master_app.brandaddress'),
        # ),
    ]
