# Generated by Django 4.1 on 2024-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0061_remove_company_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='shipping_address',
        ),
    ]
