# Generated by Django 4.1 on 2024-03-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0062_remove_companyaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_company_address', to='master_app.brandaddress'),
        ),
        migrations.AddField(
            model_name='pos',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_pos_billing_address', to='master_app.brandaddress'),
        ),
        migrations.AddField(
            model_name='pos',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_pos_shipping_address', to='master_app.brandaddress'),
        ),
    ]
