# Generated by Django 4.1 on 2024-04-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0063_companyaddress_address_pos_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btobclient',
            name='is_msme_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='btobclient',
            name='msme_registration_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='btobclient',
            name='udyam_number',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_msme_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='msme_registration_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='udyam_number',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='udyam_number',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
