# Generated by Django 4.1 on 2024-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0066_purchased_submitted_alter_purchased_purchase_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
