# Generated by Django 4.1 on 2024-05-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0067_purchased_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitems',
            name='uom',
            field=models.CharField(default='KG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='default_uom_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='not_received_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='received_beyond_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseditems',
            name='uom',
            field=models.CharField(default='KG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialuommodel',
            name='recipe_conversion_ratio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
