# Generated by Django 4.1 on 2024-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0068_poitems_uom_poplanningmaterial_default_uom_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poitems',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='extra_allowed_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='poplanningmaterial',
            name='total_allowed_quantity',
            field=models.FloatField(null=True),
        ),
    ]
