# Generated by Django 4.1 on 2024-06-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0070_poplanningtemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningMaterialDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_add_new_qauntity', models.BooleanField(default=False)),
                ('allowed_quantity', models.FloatField(null=True)),
                ('total_allowed_quantity', models.FloatField(null=True)),
                ('extra_allowed_quantity', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning_material_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_material_distribution_reference', to='master_app.poplanningmaterial')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_material_distribution_store', to='master_app.store')),
            ],
            options={
                'db_table': 'po_planning_material_distribution',
            },
        ),
    ]
