# Generated by Django 4.1 on 2024-06-13 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0072_periodicautomaticreplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_issue_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('child_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_request', to='master_app.store')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_issue_issued_by', to=settings.AUTH_USER_MODEL)),
                ('parent_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_issued', to='master_app.store')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_issue_requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_issue',
            },
        ),
        migrations.CreateModel(
            name='StoreIssueItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=240)),
                ('default_uom', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField()),
                ('ordered_qauntity', models.FloatField(default=0)),
                ('issued_qauntity', models.FloatField(default=0)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_remark', models.CharField(max_length=240, null=True)),
                ('remark', models.CharField(max_length=240, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_store_issue', to='master_app.rawmaterialregistrationmodel')),
                ('store_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_issue_materials', to='master_app.storeissue')),
            ],
            options={
                'db_table': 'store_issue_items',
            },
        ),
    ]
