# Generated by Django 4.1 on 2024-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0073_storeissue_storeissueitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeissue',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeissue',
            name='issued_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storeissue',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeissue',
            name='recieved_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storeissue',
            name='submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storeissueitems',
            name='recieved_qauntity',
            field=models.FloatField(default=0),
        ),
    ]
