# Generated by Django 4.1 on 2024-06-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0074_storeissue_issued_storeissue_issued_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeissue',
            old_name='recieved_on',
            new_name='received_on',
        ),
        migrations.RenameField(
            model_name='storeissueitems',
            old_name='recieved_qauntity',
            new_name='received_qauntity',
        ),
    ]
