# Generated by Django 4.1 on 2024-06-15 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0075_rename_recieved_on_storeissue_received_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_transfer_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(null=True)),
                ('received', models.BooleanField(default=False)),
                ('received_on', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_department_stock_transfer', to='master_app.department')),
                ('from_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pos_stock_transfer', to='master_app.pos')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by_stock_transfer', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_department_stock_transfer', to='master_app.department')),
                ('to_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pos_stock_transfer', to='master_app.pos')),
                ('transfered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_by_stock_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_transfer',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=240)),
                ('default_uom', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField()),
                ('issued_qauntity', models.FloatField(default=0)),
                ('received_qauntity', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=240, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_final_product', to='master_app.finalproductregistrationmodel')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_raw_materials', to='master_app.rawmaterialregistrationmodel')),
                ('semi_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_semi_product', to='master_app.semiproductregistrationmodel')),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_materials', to='master_app.stocktransfer')),
            ],
            options={
                'db_table': 'stock_transfer_items',
            },
        ),
    ]
