# Generated by Django 4.1 on 2024-07-07 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0076_stocktransfer_stocktransferitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.BooleanField(default=False)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('order_sheet_id', models.CharField(max_length=100, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(null=True)),
                ('issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(null=True)),
                ('received', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_sheet', to=settings.AUTH_USER_MODEL)),
                ('from_b2b_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_client_requested_order_sheet', to='master_app.btobclient')),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_requested_order_sheet', to='master_app.department')),
                ('from_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_requested_order_sheet', to='master_app.pos')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_order_sheet', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_order_sheet', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_order_sheet', to='master_app.department')),
                ('to_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_order_sheet', to='master_app.pos')),
            ],
            options={
                'db_table': 'order_sheet',
            },
        ),
        migrations.CreateModel(
            name='OrderSheetItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=240)),
                ('default_uom', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField()),
                ('issued_qauntity', models.FloatField(default=0)),
                ('received_qauntity', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=240, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sheet_final_product', to='master_app.finalproductregistrationmodel')),
                ('order_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sheet_materials', to='master_app.ordersheet')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sheet_raw_materials', to='master_app.rawmaterialregistrationmodel')),
                ('semi_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sheet_semi_product', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'order_sheet_items',
            },
        ),
    ]
