# Generated by Django 4.1 on 2024-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0077_ordersheet_ordersheetitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheetitems',
            name='ordered_qauntity',
            field=models.FloatField(default=0),
        ),
    ]
