# Generated by Django 4.1 on 2024-07-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0078_ordersheetitems_ordered_qauntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersheetitems',
            old_name='issued_qauntity',
            new_name='issued_quantity',
        ),
        migrations.RenameField(
            model_name='ordersheetitems',
            old_name='ordered_qauntity',
            new_name='ordered_quantity',
        ),
        migrations.RenameField(
            model_name='ordersheetitems',
            old_name='received_qauntity',
            new_name='received_quantity',
        ),
        migrations.RenameField(
            model_name='stocktransferitems',
            old_name='issued_qauntity',
            new_name='issued_quantity',
        ),
        migrations.RenameField(
            model_name='stocktransferitems',
            old_name='received_qauntity',
            new_name='received_quantity',
        ),
        migrations.RenameField(
            model_name='storeissueitems',
            old_name='issued_qauntity',
            new_name='issued_quantity',
        ),
        migrations.RenameField(
            model_name='storeissueitems',
            old_name='ordered_qauntity',
            new_name='ordered_quantity',
        ),
        migrations.RenameField(
            model_name='storeissueitems',
            old_name='received_qauntity',
            new_name='received_quantity',
        ),
    ]
