# Generated by Django 4.1 on 2024-08-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0081_alter_stocktransfer_received_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=240)),
                ('default_uom', models.CharField(max_length=100)),
                ('default_uom_quantity', models.FloatField()),
                ('ordered_quantity', models.FloatField(default=0)),
                ('issued_quantity', models.FloatField(default=0)),
                ('received_quantity', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=240, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_final_product', to='master_app.finalproductregistrationmodel')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='master_app.ordersheet')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_raw_materials', to='master_app.rawmaterialregistrationmodel')),
                ('semi_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_semi_product', to='master_app.semiproductregistrationmodel')),
            ],
            options={
                'db_table': 'production_items',
            },
        ),
        migrations.CreateModel(
            name='ProductionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(max_length=100, null=True)),
                ('production_date', models.DateTimeField(null=True)),
                ('direct_order', models.BooleanField(default=False)),
                ('production_type', models.CharField(max_length=100, null=True)),
                ('from_b2b_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_client_production_data', to='master_app.btobclient')),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_requested_production', to='master_app.department')),
                ('from_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_requested_production', to='master_app.pos')),
                ('order_sheet_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sheet_productions', to='master_app.ordersheet')),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_productions', to='master_app.department')),
                ('to_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_productions', to='master_app.pos')),
            ],
            options={
                'db_table': 'productions',
            },
        ),
    ]
