# Generated by Django 4.1 on 2024-08-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0082_productionitems_productiondetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionitems',
            old_name='issued_quantity',
            new_name='produced_quantity',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='received_quantity',
        ),
        migrations.AddField(
            model_name='storeissue',
            name='to_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_department_store_issue', to='master_app.department'),
        ),
        migrations.AddField(
            model_name='storeissue',
            name='to_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_pos_store_issue', to='master_app.pos'),
        ),
        migrations.AlterField(
            model_name='storeissue',
            name='child_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_issue_request', to='master_app.store'),
        ),
    ]
